# Generated by Django 3.0.4 on 2020-04-06 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_messagefile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='file',
        ),
    ]
