# Generated by Django 2.1.5 on 2019-02-25 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20190221_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to='attachment/'),
        ),
        migrations.AlterField(
            model_name='message',
            name='seen',
            field=models.BooleanField(default=True),
        ),
    ]
