# Generated by Django 2.1.5 on 2019-02-26 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20190225_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='typing',
            field=models.BooleanField(default=False),
        ),
    ]
