export const HOME = '/'
export const SIGN_IN = '/login'
export const SIGN_UP = '/signup'
export const DASHBOARD = '/dashboard'
export const ROOM = '/dashboard/:id'
export const PROFILE = '/profile'
export const CONFIRM_EMAIL = '/confirm-email'
export const RESET_PASSWORD = '/reset-password/:uid/:confirmToken'
